### ISSUE TITLE
assert.rejects and assert.doesNotReject

### ISSUE THREAD

**Issue by mysticatea** [sindresorhus/core-assert#3]
Node.js 10.0.0 added two functions: [assert.rejects](https://nodejs.org/api/assert.html#assert_assert_rejects_block_error_message) and [assert.doesNotReject](https://nodejs.org/api/assert.html#assert_assert_doesnotreject_block_error_message).
Does this package have a plan to support those?

**Comment by sindresorhus** [comment]
No, I don't use this anymore nor have the time to maintain it. Happy to transfer it if you want to. Otherwise, I'm just gonna mark it as deprecated.

**Comment by sindresorhus** [comment]
It's now deprecated.
